# Generated by Django 5.2.6 on 2025-09-24 22:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('funcionario', 'Funcionário'), ('gerente', 'Gerente'), ('admin', 'Adiministrador')], default='funcionario', max_length=20),
        ),
    ]
