# Generated by Django 5.2.6 on 2025-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='resource',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tipo',
            field=models.CharField(choices=[('dispositivo', 'Dispositivo'), ('equipamento', 'Equipamento'), ('veiculo', 'Veículo')], max_length=20),
        ),
    ]
