# Generated by Django 5.2.6 on 2025-09-24 22:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_criado_em_alter_resource_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
